spring.application.name=api-gateway
server.port=8080
spring.main.web-application-type=reactive

# Route: Advertiser Service
spring.cloud.gateway.routes[0].id=advertiser-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/advertiser/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# Route: Analytics Service
spring.cloud.gateway.routes[1].id=analytics-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/analytics/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

# Route: Feed Service
spring.cloud.gateway.routes[2].id=feed-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/feeds/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

# Actuator Monitoring
management.endpoints.web.exposure.include=*
